#!/bin/bash -f
#  "Usage: mkenv filename filename-root"
#  Create an envelope file from a correlate file
#  The output correlate filename is the same as the input filename with
#  the prefix "env-".   e.g.   env-filename.
#
#  This script must be run in the same directory as the input file.
#  Filename root is just the filename without a file extension.
#
#  Note that no filter or decimation is done here.
if [ $# != 1 ]; then
    echo "Usage: mkenv filename"
    exit 1
fi
FILE=$1
STEM=${FILE%.*}

sioseis << EOF
procs diskin header t2f f2t gains header2 prout diskoa end
diskin
  ipath segy/$FILE
  #delay 
  renum 1  end
end
header
    i120 = i58    ! save the original trace length
    fno 0 lno 999999999 ftr 0 ltr 999999999 end
end
header2 
    i58 = i120    ! restore the original trace length
    fno 0 lno 999999999 ftr 0 ltr 999999999 end
end
prout
  info 1      ! print plotting info
   fno 0 lno 999999999 noinc 100 end    ! print every 20th trace
end
gains
   type 7 end  ! complex modulus - make envelope from analytic
end
t2f
   end     ! number of sample is the next power of two larger than the input
end
f2t
   type analytic end   ! create the complex trace
end
filter
ftype 0 pass 2 500 dbdrop 48 end
end
diskoa
   opath env-segy/env-$STEM.sgy  end
end
end
EOF
